serverless-now/handler.js, serverless-now/package-lock.json, serverless-now/package.json, serverless-now/serverless.yml
Changes:
* Now importing the @uoa/utilities node module.
* Lambda GET method now requires authorization. 
* Returns user data if lambda get request contains valid authorization.
=> Authorized User info access

.gitignore, Jenkinsfile, cer-graphql/.env.example, cer-graphql/config.json, cer-graphql/index.js, cer-graphql/package-lock.json, cer-graphql/package.json, cer-graphql/tests/integration-tests.test.js
Add placeholder Jenkinsfile vars and change cer-graphql to get variables from file, to enable local development.
=> Add placeholder Jenkinsfile vars and change cer-graphql to get variables from file

Jenkinsfile, research-hub-web/src/app/graphql/possible-types.ts, research-hub-web/src/app/graphql/schema.ts
Adding a line to allow for 'sandbox-' prefixed branches to be picked up for deployment by jenkins.
=> Jenkins hotfix

cer-graphql/tests/integration-tests.test.js, serverless-now/test/main.js
Fixes the requested changes to integration testing that weren't included in the integration testing merge.
=> Integration test improvements

Jenkinsfile
Changes to the Jenkinsfile to allow for faster deployment by reusing node modules where appropriate.
=> Added node modules changes rather than adding 20 commits from sandbox.

Jenkinsfile
* Re-enables Slack notifications when the Jenkins job executes successfully (which were accidentally disabled)
=> Re-enabled Jenkins success post message

terraform/README.md, terraform/cognito.tf, terraform/elastic-search-domain.tf, terraform/envs/its-nonprod/hub-test.tfvars, terraform/envs/its-prod/hub-prod.tfvars, terraform/envs/sandbox/hub-dev.tfvars, terraform/variables.tf
Minor update to cognito setup to include the 2fab url in the callbacks. Required for integration testing to work.
=> Terraform Updates

hub-search-proxy/handler.js, research-hub-web/cypress/integration/fundings.e2e.js, research-hub-web/src/app/components/fundings/funding-purpose/funding-purpose.component.html, research-hub-web/src/app/components/fundings/funding-purpose/funding-purpose.component.spec.ts, research-hub-web/src/app/components/fundings/funding-purpose/funding-purpose.component.ts, research-hub-web/src/app/components/fundings/funding-routing.module.ts, research-hub-web/src/app/components/fundings/fundings.component.html, research-hub-web/src/app/components/fundings/fundings.component.scss, research-hub-web/src/app/components/fundings/fundings.component.spec.ts, research-hub-web/src/app/components/fundings/fundings.component.ts, research-hub-web/src/app/components/fundings/fundings.module.ts, research-hub-web/src/app/components/search-bar/search-bar.service.ts, research-hub-web/src/app/components/shared/body-media/body-media.component.html, research-hub-web/src/app/components/shared/collection-list/collection-list.component.ts, research-hub-web/src/app/graphql/fragments/public-fields.fragment.graphql, research-hub-web/src/app/graphql/queries/all-funding-slugs.query.graphql, research-hub-web/src/app/graphql/queries/all-funding.query.graphql, research-hub-web/src/app/graphql/queries/get-funding-by-slug.query.graphql, research-hub-web/src/app/graphql/queries/get-funding-purpose-by-slug.query.graphql, research-hub-web/src/app/routing/routing.ts, research-hub-web/src/styles.scss
Adding the new page type, Funding
Includes two new components:
- Fundings
- Funding Purpose
Unit tests and e2e tests added. Unit tests passing. e2e not sure - tests aren't running well. Will need to merge in the CSS and test optimisations, and update the tests and component style files before this is merged.
=> Funding page

Jenkinsfile, research-hub-web/cypress/integration/articles.e2e.js, research-hub-web/cypress/integration/caseStudy.e2e.js, research-hub-web/cypress/integration/equipment.e2e.js, research-hub-web/cypress/integration/events.e2e.js, research-hub-web/cypress/integration/fundings.e2e.js, research-hub-web/cypress/integration/routing.e2e.js, research-hub-web/cypress/integration/search.e2e.js, research-hub-web/cypress/integration/service.e2e.js, research-hub-web/cypress/integration/software.e2e.js, research-hub-web/cypress/integration/subhubs.e2e.js, research-hub-web/src/app/graphql/queries/get-funding-by-slug.query.graphql
- Improve e2e tests to depend (less) on specific content
- Enable e2e tests
=> Better e2e tests

research-hub-web/src/app/components/equipments/equipment.component.html, research-hub-web/src/app/components/softwares/softwares.component.html, research-hub-web/src/app/graphql/queries/get-funding-by-slug.query.graphql
Minor changes to display fields that were omitted from templates.
=> Template missing fields

Jenkinsfile, research-hub-web/cypress.json, research-hub-web/package.json
Fixes for tests timeouts, retries, disabling case study and funding e2e tests until content is actually published in prod environment.
=> Hot fix e2e timeout

Jenkinsfile
Reordered Jenkins pipeline so web project builds last
=> Reordered pipeline so web project builds last

hub-search-proxy/handler.js, research-hub-web/package.json, research-hub-web/src/app/graphql/queries/all-pages.query.graphql, research-hub-web/src/app/graphql/queries/all-searchable-content.query.graphql, research-hub-web/src/app/graphql/queries/all-subhub-child-pages-slugs.query.graphql
Funding breadcrumbs now show subhubs association
Minor clean up of content types in the search lambda
=> Fix funding breadcrumbs

research-hub-web/src/app/components/search-page/search-page.component.html
=> fix org filter menu on search page

research-hub-web/src/app/components/shared/body-media/body-media.component.html, research-hub-web/src/app/components/shared/cards/cards.component.html, research-hub-web/src/app/components/shared/collection-list/collection-list.component.html, research-hub-web/src/app/components/shared/large-cards/large-cards.component.html
=> update padlock display behaviour

.github/workflows/linting.yml, research-hub-web/src/app/app.component.ts
This enables a github workflow that checks `ng lint` for errors for pull requests and pushes to `master`. I've tested the workflow locally with [act](https://github.com/nektos/act) and it seems to work as intended. Here are some instructions for how to run act:
1. Install docker
2. Install act (instructions in link above)
3. Rename .env file in `hub-stack` so that act doesn't pick it up automatically
4. run `act`
Sidenote: This could easily be extended to run all our tests as well!
=> Enable linting workflow

research-hub-web/src/app/components/search-bar/search-bar.service.ts
=> add sort option to search analytics datalayer

research-hub-web/src/app/graphql/queries/all-articles-slugs.query.graphql
hotfix all articles slug query
=> Hotfix All Articles Slugs

research-hub-web/src/styles.scss
Bullet lists now displaying correctly on Firefox and Safari
=> Hot fix cross browser

.github/workflows/tests.yml, README.md
This is just for testing the angular unit test workflow
=> Ng test workflow 

.github/dependabot.yml
setting up dependabot version updates
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates
=> add dependabot yml for Version Updates

research-hub-web/src/app/components/layout/notification/notification.component.ts
This PR implements hiding of the notification when there is no content to show.
=> Handle empty notification

research-hub-web/src/app/app.component.spec.ts, research-hub-web/src/app/app.material.module.ts, research-hub-web/src/app/components/layout/navbar/navbar.component.html, research-hub-web/src/app/components/layout/navbar/navbar.component.scss, research-hub-web/src/styles.scss
- Hide the unnecessary detail
- Remove the mat-menu
=> Login menu update

research-hub-web/src/app/app.module.ts, research-hub-web/src/app/components/activities-page/activities-page.component.ts, research-hub-web/src/app/components/categories-page/categories-page.component.ts, research-hub-web/src/app/components/home/home.component.spec.ts, research-hub-web/src/app/components/home/home.component.ts
Handles the authentication networkError returned from the graphql server which affects the preview environment loading.
Also adds some error handling for the home page, categories page, and activities page.
=> Hotfix auth network error

research-hub-web/src/app/components/layout/search-filters/search-filters.component.html
This PR adds counters to the tab labels in the search filter UI indicated how many filters are selected.
=> added filter counter to tab labels

research-hub-web/cypress/integration/software.e2e.ts
Software page url in test script does not exist in ResearchHub Prod
=> Update software test url

cer-graphql/package.json, hub-search-proxy/package.json, research-hub-web/package.json, research-hub-web/src/app/components/layout/search-filters/search-filters.component.html
=> Change activities label to research stage

research-hub-web/src/app/components/activities-page/activities-page.component.html, research-hub-web/src/app/graphql/queries/all-research-stages.query.graphql
=> RSM-3036: stage: replace search with url
